name: Build OpenWrt Decryptor (musl)

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: amurcanov/happ-decrypt-universal

      - name: Fix Rust edition version
        run: |
          sed -i 's/edition = "2026"/edition = "2021"/g' Cargo.toml
          sed -i 's/edition = "2024"/edition = "2021"/g' Cargo.toml

      - name: Compile using rust-musl-cross
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/rust/src messense/rust-musl-cross:aarch64-musl cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: happ-decrypt
          path: target/aarch64-unknown-linux-musl/release/happ-decrypt-universal
