name: Build OpenWrt Decryptor (musl)

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: amurcanov/happ-decrypt-universal

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-musl

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install cargo-zigbuild
        run: pip3 install cargo-zigbuild

      - name: Compile for aarch64-musl (OpenWrt)
        run: cargo zigbuild --release --target aarch64-unknown-linux-musl

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: happ-decrypt
          path: target/aarch64-unknown-linux-musl/release/happ-decrypt-universal
